### ISSUE TITLE
Félicitations

### ISSUE THREAD

**Issue by jerife98** [kengnidoriane/my_first_website#1]
Bravo à toi Miss! Tu viens de valider ton premier programme. Place maintenant à Pico j'espère que tu feras pareil qu'ici :clap: :clap:

**Comment by kengnidoriane** [comment]
> Bravo à toi Miss! Tu viens de valider ton premier programme. Place maintenant à Pico j'espère que tu feras pareil qu'ici 👏 👏

Merci 😊. J'espère aussi qu'avec pico ça va aller dans la mme lancée
